### ISSUE TITLE
BlockDestructionService needs a rework

### ISSUE THREAD

**Issue by GurteX** [3arthqu4ke/phobot#11]
BlockDestructionService is VERY VERY BAD!!!!! you CANT have more active blocks than players around you!!!! if theres 1 player and he mines 10 blocks they are going to stay... why?? Maybe actually check if someone mining a block or no, so you need to always update its status?? idk so like if u got 100% progress and no1 be mining it for more than specific amount of time just remove it cuz nobody is mining that anywaysss

**Comment by 3arthqu4ke** [comment]
Iwaslikeucanneverknowmaybehehasasuperdupernewspeedminemoduleandcanmine10blockssoiwaslikewhateveruknowwhaimsayin

**Comment by GurteX** [comment]
Also a module related to that BLOCKER!!!!! it does some stupid sh very often.u cn just walk somwhere wit mined blocks around and its gonna sht with blocks

**Comment by GurteX** [comment]
@3arthqu4ke

**Comment by GurteX** [comment]
https://discord.com/channels/@me/1023693325150199908/1209900353483440199
