### ISSUE TITLE
Instant speedmine and grim option 

### ISSUE THREAD

**Issue by aidr0b** [3arthqu4ke/phobot#29]
we can use instant mine on cc, and blocks can be mined faster. 
Also limit BlockDestructionService to a maximum of (n.o. players * 2) blocks. It also should remove positions if no player is in a 6 block radius of that block.

**Comment by GurteX** [comment]
I will add instant mine and faster mining, but limiting blocks amount in BlockDestructionService can be easily overlooked and should not be implemented as it might cause issues.
