### ISSUE TITLE
Please send the jar with the instantmine

### ISSUE THREAD

**Issue by boopx3** [3arthqu4ke/phobot#32]
@GurteX Could you please provide me the jar that has the instantmine added

**Comment by GurteX** [comment]
1. Open Intellij
2. New Project -> Get from VCS
3. Copy "https://github.com/GurteX/Phobot.git"
4. Next to the project name where it says main, click on that, open "remote" dropdown, select patch-5, and click "Checkout"
5. Run Phobot/fabric/Tasks/build/build (Only after you have no running processes such as indexing)
