### ISSUE TITLE
how to install phobot?

### ISSUE THREAD

**Issue by loveblindness** [3arthqu4ke/phobot#34]

**Comment by loveblindness** [comment]
Hello, I'm 2young2care. after watching 3arthqu4ke's video I saw phobot, I really want to use it but don't know how to install it, please help me. thank you.

**Comment by GurteX** [comment]
> Hello, I'm 2young2care. after watching 3arthqu4ke's video I saw phobot, I really want to use it but don't know how to install it, please help me. thank you.

First step is to install pingbypass, the best way is to install intellij idea, clone the repository, and build it yourself, after that, you can find the jar file in either fabric/build/libs or forge/build/libs depending on what you're running, fabric or forge respectively, after running your game, folder pingbypass will appear in .minecraft, same with phobot, build, get fabric or forge build, and put it in pingbypass/plugins directory. (pingbypass should be in .minecraft/mods, and phobot in .minecraft/pingbypass/plugins)

**Comment by loveblindness** [comment]
Thank you !
