### ISSUE TITLE
is there any possible methods to disable auto=switch?

### ISSUE THREAD

**Issue by IronExeption** [3arthqu4ke/phobot#36]
crystal is switching to offhand during +AutoTotem Mode Totem and causes kick from server, if it's possible to disable switch in AutoCrystal please tell me

**Comment by 3arthqu4ke** [comment]
No, sorry. 

You could take this line: 
https://github.com/3arthqu4ke/phobot/blob/8b3528f5fd18879b54aab7617d98c9a06758cda4/src/main/java/me/earth/phobot/modules/combat/autocrystal/CrystalPlacingAction.java#L107
and add a check for if you are holding a crystal, if not, return, pair that with a simple boolean setting, done, I think.
